name: real_estate
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  rename: ^2.1.1
  equatable: ^2.0.5
  flutter_screenutil: ^5.7.0
  pinput: ^2.2.31
  dotted_border: ^2.0.0+3
  #dots_indicator: ^2.1.0
  carousel_slider: ^4.2.1
  expandable_page_view: ^1.0.17
  #scroll_navigation: ^1.3.2
  readmore: ^2.2.0
  #transformable_list_view: ^0.3.0
  #animation_list: ^2.2.1
  dartz: ^0.10.1
  dots_indicator: ^2.1.0
  # for state management
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  lottie: ^2.3.2
  auto_size_text: ^3.0.0
  image_picker: ^0.8.7+5
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.11
  #flutter_credit_card: ^3.0.6
  webview_flutter: ^4.2.0
  timeago: ^3.4.0
  http: ^1.1.0
  flutter_timer_countdown: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/icons/
   - assets/images/
   - assets/stripe/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21